version: '3.7'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - celery
    ports:
      - "5002:5000"
    entrypoint: flask run
    environment:
      FLASK_ENV: development

  celery:
    build:
      context: .
    entrypoint: celery worker -A app --loglevel=info
    depends_on:
      - redis

  rabbit:
    image: rabbitmq:3.7.17-alpine